### ISSUE TITLE
如何配置中文输入法？

### ISSUE THREAD

**Issue by lnut220303082** [D-Robotics/rdk_doc#33]
使用RDK x5配置中文环境后依然没有中文输入法，问客服没有得到答案，如何解决？

**Comment by wei-jin-fang** [comment]
> 使用RDK x5配置中文环境后依然没有中文输入法，问客服没有得到答案，如何解决？

您好，您是桌面端还是Server端呢，记得配置完成之后要重启使用sudo reboot 进行生效，如果还不行，能否提供相关截图呢？

**Comment by wei-jin-fang** [comment]
> 之后



> 使用RDK x5配置中文环境后依然没有中文输入法，问客服没有得到答案，如何解决？

我猜您可能想是安装一个中文输入法，手册的是将环境的语言设置为中文，您看能否提供一些跟多的信息或者截图吗

**Comment by xuguosheng110** [comment]
您好 长期没有得到回复，我们暂时先关闭issue 后续您有需求，我们进行更新
