### ISSUE TITLE
建议修改下部署PC上docker开发环境的流程

### ISSUE THREAD

**Issue by rainote2020** [D-Robotics/rdk_doc#38]
位置：[environment_config.md](https://github.com/D-Robotics/rdk_doc/blob/main/docs/07_Advanced_development/04_toolchain_development/intermediate/environment_config.md)
这里面一些信息过时了。

第一个问题：宿主机docker环境配置

> 使用Docker环境
为了帮助您快速使用算法工具链，D-Robotics 提供了包含完整开发环境的Docker镜像，大大简化了环境的部署过程。
在阅读此部分内容前，我们希望您的开发机中已经预装好了Docker的基础环境。 D-Robotics 要求的Docker基础环境信息如下：
Docker（>=1.12 建议安装18.03.0-ce）, 安装手册 [https://docs.docker.com/install/。](https://docs.docker.com/install/%E3%80%82)
NVIDIA Docker（2.0.3），安装手册[NVIDIA/nvidia-docker](https://github.com/nvidia/nvidia-docker/wiki)。

正常安装cuda，如果是网络源的形式，直接apt install  nvidia-container-toolkit即可，否则可按照官方指导：https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt
但国内环境下网络源安装是最简单的。

docker目前的install指南:https://docs.docker.com/engine/install/ubuntu/#installation-methods
这里没有任何必要指定ce版本docker。不用docker-compose、轻度使用直接install docker.io就够了。会用docker-compose的也不需要看这一段指南。

第二个：启动容器命令

>   docker run -it **--runtime=nvidia -e NVIDIA_DRIVER_CAPABILITIES=compute,utility \
    -e NVIDIA_VISIBLE_DEVICES=all** --rm --shm-size="15g" \
    -v "$ai_toolchain_package_path":/open_explorer \
    -v "$dataset_path":/data \
    openexplorer/ai_toolchain_ubuntu_20_x3j5_gpu:"${version}"

其中```
--runtime=nvidia -e NVIDIA_DRIVER_CAPABILITIES=compute,utility \
    -e NVIDIA_VISIBLE_DEVICES=all
```等效`--gpus=all`。并且在新版docker(>19)环境下会报错，无法接受`--runtime=nvidia`。

参考：https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html
![image](https://github.com/user-attachments/assets/b14eaf86-99f8-498b-bda6-acb9013fdce8)

**Comment by xuguosheng110** [comment]
收到，感谢您的反馈，我们会进行内容的调整

**Comment by xuguosheng110** [comment]
您好 我们已经修改了内容，请及时查阅，issue我们会进行关闭，有问题我们可以继续沟通
